### ISSUE TITLE
How read ini-data from string value?

### ISSUE THREAD

**Issue by khusamov** [evangelion1204/multi-ini#17]

**Comment by evangelion1204** [comment]
Hi, do you want to read/parse a string instead of a file?

**Comment by khusamov** [comment]
yes

**Comment by evangelion1204** [comment]
With version 1.0.0 its planned to split the code and extract a parser. But currently its not supported. If you require it then its a good reason to finally migrate the almost done code.

**Comment by khusamov** [comment]
Thanks for the answer! We are waiting for the new version)
