### ISSUE TITLE
quoting problem

### ISSUE THREAD

**Issue by krzysztofantczak** [evangelion1204/multi-ini#24]
Hey,

In short, this is my source file:
```
[rabbitmq]
server_ip=127.0.0.1
server_port=5672
user=guest
password=guest
exchangeName=emailMessages
exchangeType=direct
confirm=true
durable=true
autoDelete=true
deliveryMode=2
queueName=emails
```

And this is what i get after ini.write
```
[rabbitmq]
server_ip="localhost"
server_port="2525"
user="guest"
password="guest"
exchangeName="emailMessages"
exchangeType="direct"
confirm="true"
durable="true"
autoDelete="true"
deliveryMode="2"
queueName="emails"
```

No matter what i set in keep_quotes, result is the same - all values are quoted. I had to disable needToBeQuoted function to make this work - as for my use case, i don't need quotes at all.

**Comment by evangelion1204** [comment]
Hi,

Currently `keep_quotes` was just a parser option that included quotes in the parsed string. You are probably right that this option should also affect the serialize and produce a non quoted output.

In any case I could fix this behaviour which would make sense but break backward compatibility in some point or add a new option like `disable_quoting` or whatever else as a workaround for now.

I need to evaluate this first.

**Comment by krzysztofantczak** [comment]
TBH i'm using this module only for editing already existing ini files. So it would be awesome if it could keep quoted fields quoted and do not quote fields that weren't quoted in the first place.

**Comment by evangelion1204** [comment]
@krzysztofantczak the newest version 1.0.1 should fix your issue.
