### ISSUE TITLE
Dependent upon node? fs is not available in nashhorn

### ISSUE THREAD

**Issue by ComLock** [evangelion1204/multi-ini#26]
This line means multi-ini is basically dependant upon Node:
https://github.com/evangelion1204/multi-ini/blob/a46b66e5390ca897ee98204e339dd8393b619d8c/src/multi-ini-class.js#L3
```es2015
const fs = require('fs');
```

Since I've already read the ini file into a string, I thought: let me work around it using the parser directly. But that landed me in ReferenceError: "Symbol" is not defined.

Which indicate to me this is Ecmascript 2015 dependant aswell.

So in a Java Nashorn environment this module cannot be used.

Next version of java's js engine should support Ecma 2015, so maybe then I can at least use the parser.

**Comment by evangelion1204** [comment]
Hi, sorry for the late response. I am not sure if this is possible but in Node you can import via path. like:
```js
var Parser = require('multi-ini/lib/parser.js');
```

**Comment by ComLock** [comment]
The point was rather that I'm not using Node... I'm using Java Nashorn. Which does not have a global object and more... The multi-ini module is currently dependant upon Node, which is not reflected in package.json... Where only lodash is listed as a dependancy. This is misleading for all people that is not using Node...

**Comment by evangelion1204** [comment]
Yeah, I got that. 
I used vert.x in the past. I just mean you could try the require via path if this is working in `Nashorn`. Besides that I can add a minimum Node.js version to the `engine` settings of the `package.json`.
But would that help to make the dependency to Node.js clear? I never saw a built in module like `fs` in the `package.json`, not even sure if this is even possible.

**Comment by ComLock** [comment]
Yeah I'm not an expert on package.json either.

And the fs package isn't the node builtin. And currently has a weird message:
```Security holding package
This package name is not currently in use, but was formerly occupied by another package. To avoid malicious use, npm is hanging on to the package name, but loosely, and we'll probably give it to you if you want it.

You may adopt this package by contacting support@npmjs.com and requesting the name.```
https://www.npmjs.com/package/fs

As node alternatives are popping up, the node dependancy "mess" should have best practice solutions. I don't have the answer for that one though. Just pointing it out, hoping node people will care to figure it out.
