### ISSUE TITLE
line parsing breaks

### ISSUE THREAD

**Issue by rijnhard** [evangelion1204/multi-ini#27]
So I was looking at moving away from `ini` since isaacs hasn't responded to my PR in forever. 

I am using a custom filter for Zend Boolean values:
```es
function decodeZendBoolean(value) {
    if (typeof value !== 'string' || value.length > 5) {
        return value;
    }

    switch (value.toLowerCase()) {
        case 'on':
        case 'yes':
        case 'true':
            return true;
        case 'off':
        case 'no':
        case 'none':
        case 'false':
            return false;
        default:
            return value;
    }
}
```

using this data set

```ini
; all of these work
[section_true]
boolean1 = on
boolean2 = On
boolean3 = yes
boolean4 = Yes
boolean5 = true
boolean6 = True
boolean7 = TRUE

; some of these work
[section_false]
boolean1 = off
boolean2 = Off
boolean3 = no
boolean4 = No
; parsing fails here and values never hit the custom filter, so they stay strings
boolean5 = false
boolean6 = False
boolean7 = FALSE

[section_normal]
t1 = what
t2 = 3
t4 = "sweet"
```

**Comment by evangelion1204** [comment]
Hi, sorry for the late response. Was very occupied and will check what is going on.

**Comment by evangelion1204** [comment]
I am not sure but might be that your decoder is wrong
```js
        function decodeZendBoolean(value) {
            if (typeof value !== 'string' || value.length > 5) {
                return value;
            }

            switch (value.toLowerCase()) {
                case 'on':
                case 'yes':
                case 'true':
                    return true;
                case 'off':
                case 'no':
                case 'none':
                case 'false':
                    return false;
                default:
                    return value;
            }
        }
```

Was working - cause `False` is longer than 4 characters and setting it in your decoder to 5 works nicely.

**Comment by rijnhard** [comment]
I fixed that already didn't I? I'll double check, I remember having to fix
it when I added more tests recently

**Comment by rijnhard** [comment]
@evangelion1204 you are right, in the example I posted it is broken, I couldn't wait and ended up posting my own lib, but I'll update the PR anyway

**Comment by rijnhard** [comment]
@evangelion1204 sorry for all the brain farts. you are correct. I ended up using my own lib because I was in a rush, then discovered the same bug and fixed it on my end. but I'll probably move away to yours if there's no adoption.

**Comment by rijnhard** [comment]
@evangelion1204 added PR's if you want to want to accept this functionality.
