### ISSUE TITLE
feature: add section inheritance

### ISSUE THREAD

**Issue by ni-do** [evangelion1204/multi-ini#32]
Hi there,

i would like to add section inheritance for the project, like known from ini processing within the php Zend Framework f.e., like:

`[myparentsection]`
modulename.mykey1 = value
modulename.mykey2 = value

`[mychildsection:myparentsection]`
modulename.mykey1 = othervalue

the child section would then contain all values from the parent section (i.e. mykey1 and mykey2) and one would be able to override values with the same name (i.e. mykey1 would be overwritten.

Please give me a reply if you're fine with me setting a pull request for it.

Greetings!

**Comment by ni-do** [comment]
Hi again,

might this feature be of any interest for someone? @evangelion1204 Thank you very much for your soon reply.

Regards

**Comment by evangelion1204** [comment]
I think I never used that feature of Zend - I will come back to that in the PR.

**Comment by evangelion1204** [comment]
Merged and made a small adjustment to the regex. Thx a lot :)
