### ISSUE TITLE
Feature: integer converter filter

### ISSUE THREAD

**Issue by rijnhard** [evangelion1204/multi-ini#44]
code looks something like this

```javascript
function intConverter(value) {
    if (isNaN(value)
        || isNaN(parseInt(value, 10))
        || (value.length > 1 && value[0] === '0') // dont drop zero prefixes
    ) {
        return value;
    }

    return parseInt(value, 10);
}
```

it would benefit from a `keep_zero_prefix` option to control whether you want to convert items that start with a zero or not.

**Comment by evangelion1204** [comment]
I will check it and try to understand. Problem with the keep would that storing meta information per key is required. But also here let me have a look 😄

**Comment by rijnhard** [comment]
honestly I would just try to find a way to give the filters access to the settings object provided when you create a MultiIni instance, maybe a second param? then its fully backwards compatible

**Comment by evangelion1204** [comment]
I just realized there is already access to `options` for filters. Its used in the `constants` filter.

**Comment by evangelion1204** [comment]
Will publish as `2.2.0`
