### ISSUE TITLE
Multiline issue

### ISSUE THREAD

**Issue by sanglier91** [evangelion1204/multi-ini#6]
Hi ! 
I have an issue with this following configuration file : 

[C_UPu_Metal_H2O]
; loi incomplète

name="(U+Pu) métal H2O"

description="
(U+Pu) métal modération H2O
Paramétrage de la modération en H/(U+Pu)"

ruledeclaration="C_UPu_Metal_H2O <- function(Tm.U5 = 100, Tm.vPu = c(100, 0, 0, 0), Hx = 0, Tm.Pu = 0) {
  Na      <- .60221
  d.PuC   <- c(19.86, 19.943211, 20.0265383, 20.1097743) 
  d.UC    <- c(18.9196621, 19.1617)
  mmPuIso <- c(239.0522, 240.0538, 241.0568, 242.0587)
  mmUIso  <- c(235.0439, 238.0508)
  return(mget(ls(), envir=as
}"

The line "return(mget(ls(), envir=as" is interpreted as a key - value instead being part of the multiline.
Thank you for your help !

**Comment by evangelion1204** [comment]
Hi, thanks for the report, I will have look asap.

**Comment by evangelion1204** [comment]
Ok, I fixed the issue and released a new version. Can you verify the fix? I reordered the parsing and added a unit test to verify your case.

**Comment by sanglierquipue** [comment]
Hi, it looks fine now :)
