### ISSUE TITLE
Remove first and last new line

### ISSUE THREAD

**Issue by sanglierquipue** [evangelion1204/multi-ini#8]
Hi, 

can add an option to remove first and last new lines so that if the ini file looks like :

[mySection]

name="
my name

"

name is equal to "my name" instead of "\nmy name\n\n".

Thx !

**Comment by evangelion1204** [comment]
Maybe I can introduce some sort of filter that can do something like this
* trim
* uppercase
* lowercase

**Comment by evangelion1204** [comment]
See #9 and the corresponding file and basic_spec.js line 396 and following of the trim filter.

**Comment by evangelion1204** [comment]
@sanglierquipue merged and published.
